name: FD-release-apollo-builder

on:
  pull_request:
  workflow_dispatch:
    inputs:
      KERNEL_TREE_1:
        description: 'Kernel Tree'
        default: 'https://github.com/re-noroi/kernel_sm8250'
        required: true
      CODENAME:
        description: 'Phone Codename'
        default: 'apollo'
        required: true
      ANYKERNEL_URL:
        description: 'AnyKernel Url (leave blank if you dont want AnyKernel)'
        default: 'https://github.com/re-noroi/anykernel3-test'
        required: false
      CUSTOM_SED:
        description: 'Custom Kernel Version'
        default: '-FakeDreamer'
        required: false
      COMPILER:
        description: 'Choose compiler'
        required: true
        type: choice
        options:
          - neutron
          - aosp
          - aosp-21
        default: aosp
      LTO_CHOICE:
        required: true
        type: choice
        options:
          - full_lto
          - thin_lto
        default: full_lto
      OPLUS_FEATURES:
        description: 'select yes if you want oplus features'
        required: true
        type: choice
        options:
          - 'yes'
          - 'no'
        default: 'no'

jobs:
  build:
    strategy:
      matrix:
        kernel: [1, 2, 3, 4]
    runs-on: ubuntu-latest
    env:
      UPLOAD_TO_RELEASE: false

    steps:
      - name: Install Dependencies
        run: sudo apt install flex libncurses6

      - name: Download & Extract Clang
        run: |
          if [[ "${{ github.event.inputs.COMPILER }}" == "aosp" ]]; then
            wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz
            mkdir clang
            tar -xf clang.tar.gz -C clang
          elif [[ "${{ github.event.inputs.COMPILER }}" == "aosp-21" ]]; then
            wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/47e1fad3c1d7c647b49597e0ea85c5d8e43a978f/clang-r574158.tar.gz -O clang.tar.gz
            mkdir clang
            tar -xf clang.tar.gz -C clang
          else
            wget https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst -O clang.tar.zst
            mkdir clang
            unzstd -d clang.tar.zst
            tar -xf clang.tar -C clang
          fi
          
      - name: Set Kernel Environment Variables
        run: |
          echo "KERNEL_TREE=${{ github.event.inputs.KERNEL_TREE_1 }}" >> $GITHUB_ENV
          case "${{ matrix.kernel }}" in
            1) echo "KERNEL_TREE_BRANCH=next-main" >> $GITHUB_ENV ;;
            2) echo "KERNEL_TREE_BRANCH=next-susfs" >> $GITHUB_ENV ;;
            3) echo "KERNEL_TREE_BRANCH=no-ksu" >> $GITHUB_ENV ;;
            4) echo "KERNEL_TREE_BRANCH=freesia" >> $GITHUB_ENV ;;
          esac
         
      - name: Checkout Kernel via PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [[ "${{ github.event.inputs.KERNEL_TREE_1 }}" == "private" ]]; then
            REPO_URL="https://x-access-token:${GH_PAT}@github.com/re-noroi/FD-private.git"
          else
            REPO_URL="${{ github.event.inputs.KERNEL_TREE_1 }}"
          fi
          git clone --depth=1 --branch "${{ env.KERNEL_TREE_BRANCH }}" "${REPO_URL}" kernel_tree

      - name: Kernel Version
        run: |
          cd kernel_tree
          if [[ "${{ github.event.inputs.CUSTOM_SED }}" != "-FakeDreamer" ]]; then
            sed -i -e 's/CONFIG_LOCALVERSION="-FakeDreamer"/CONFIG_LOCALVERSION="${{ github.event.inputs.CUSTOM_SED }}"/' arch/arm64/configs/vendor/apollo_defconfig
          fi

      - name: Remove cycle count
        run: |
          cd kernel_tree
          sed -i '/case POWER_SUPPLY_PROP_CYCLE_COUNT:/,/break;/c\
          \tcase POWER_SUPPLY_PROP_CYCLE_COUNT:\
          \t#ifdef CONFIG_BATT_VERIFY_BY_DS28E16\
          \t\tpval->intval = fg->maxim_cycle_count;\
          \t#else\
          \t\trc = get_cycle_count(chip->counter, &pval->intval);\
          \t#endif\
          \t\tbreak;' drivers/power/supply/qcom/qpnp-fg-gen4.c
      
      - name: Apply Patches (Skip for Kernel 3)
        if: matrix.kernel != 3
        run: |
          cd kernel_tree
          bash nextpatch.sh

      - name: Revert to stock gpufreq
        if: matrix.kernel == 3 || matrix.kernel == 4
        run: |
          cd kernel_tree
          patch -p1 -f < "0001-stock-gpu-freq.patch"

      - name: Change LTO Type
        if: ${{ github.event.inputs.LTO_CHOICE == 'thin_lto' }}
        run: |
          cd kernel_tree
          sed -i -e '/# CONFIG_LTO_CLANG_THIN is not set/c\CONFIG_LTO_CLANG_THIN=y;' arch/arm64/configs/vendor/apollo_defconfig
          sed -i -e '/CONFIG_LTO_CLANG_FULL=y/c\# CONFIG_LTO_CLANG_FULL is not set;' arch/arm64/configs/vendor/apollo_defconfig

      - name: Oplus Features
        if: ${{ github.event.inputs.OPLUS_FEATURES == 'yes' }}
        run: |
          cd kernel_tree
          sed -i -e '/# CONFIG_OPLUS_PORT is not set/c\CONFIG_OPLUS_PORT=y;' arch/arm64/configs/vendor/apollo_defconfig

      - name: Apply Modifications (if modified build)
        if: matrix.kernel == 2 || matrix.kernel == 4
        run: |
          cd kernel_tree
          sed -i -e '/<2553600>,/c\<2553600>;' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2649600>,/c\//<2649600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2745600>,/c\//<2745600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<2841600>,/c\//<2841600>,' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e '/<3187200>;/c\//<3187200>;' arch/arm64/boot/dts/vendor/qcom/kona.dtsi
          sed -i -e 's/qcom,mdss-pan-physical-width-dimension = <70>;/qcom,mdss-pan-physical-width-dimension = <695>;/' arch/arm64/boot/dts/vendor/qcom/dsi-panel-j3s-37-02-0a-dsc-video.dtsi
          sed -i -e 's/qcom,mdss-pan-physical-height-dimension = <154>;/qcom,mdss-pan-physical-height-dimension = <1544>;/' arch/arm64/boot/dts/vendor/qcom/dsi-panel-j3s-37-02-0a-dsc-video.dtsi
      
      - name: Build Kernel
        run: |
          export PATH="$(pwd)/clang/bin:$PATH"
          export ARCH=arm64
          export SUBARCH=ARM64
          export KBUILD_BUILD_USER="renoroi"
          export KBUILD_BUILD_HOST="dreamstate"
          export KBUILD_BUILD_TIMESTAMP="$(TZ=UTC-7 date)"
          cd kernel_tree
          make O=out vendor/apollo_defconfig
          make O=out CC=clang -j$(nproc --all) CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1
          if [[ "${{ matrix.kernel }}" == 1 ]]; then
            cp out/arch/arm64/boot/Image.gz ../Image.gz
            mv out/arch/arm64/boot/dtbo.img ../apollo-aosp-dtbo.img
            mv out/arch/arm64/boot/dtb.img ../apollo-normal-dtb
          elif [[ "${{ matrix.kernel }}" == 2 ]]; then
            cp out/arch/arm64/boot/Image.gz ../Image.gz
            mv out/arch/arm64/boot/dtbo.img ../apollo-miui-dtbo.img
            mv out/arch/arm64/boot/dtb.img ../apollo-effcpu-dtb
          elif [[ "${{ matrix.kernel }}" == 3 ]]; then
            cp out/arch/arm64/boot/Image.gz ../Image.gz
            mv out/arch/arm64/boot/dtb.img ../apollo-normal-gpustk-dtb
          else
            mv out/arch/arm64/boot/dtb.img ../apollo-effcpu-gpustk-dtb
          fi

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel != 4
        with:
          name: kernel-${{ matrix.kernel }}-base
          path: |
            Image.gz

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel == 1
        with:
          name: kernel-part-${{ matrix.kernel }}-addon
          path: |
            apollo-aosp-dtbo.img
            apollo-normal-dtb

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel == 2
        with:
          name: kernel-part-${{ matrix.kernel }}-addon
          path: |
            apollo-miui-dtbo.img
            apollo-effcpu-dtb

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel == 3
        with:
          name: kernel-part-${{ matrix.kernel }}-addon
          path: |
            apollo-normal-gpustk-dtb

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        if: matrix.kernel == 4
        with:
          name: kernel-part-${{ matrix.kernel }}-addon
          path: |
            apollo-effcpu-gpustk-dtb

  package_anykernel:
    needs: build
    strategy:
      matrix:
        kernel: [1, 2, 3]
    runs-on: ubuntu-latest

    steps:
      - name: Download Kernel Build Image
        uses: actions/download-artifact@v4
        with:
          name: kernel-${{ matrix.kernel }}-base
          path: kernel-${{ matrix.kernel }}-base

      - name: Download Kernel Build Addon 1
        uses: actions/download-artifact@v4
        with:
          name: kernel-part-1-addon
          path: kernel-part-1-addon

      - name: Download Kernel Build Addon 2
        uses: actions/download-artifact@v4
        with:
          name: kernel-part-2-addon
          path: kernel-part-2-addon

      - name: Download Kernel Build Addon 3
        uses: actions/download-artifact@v4
        with:
          name: kernel-part-3-addon
          path: kernel-part-3-addon

      - name: Download Kernel Build Addon 4
        uses: actions/download-artifact@v4
        with:
          name: kernel-part-4-addon
          path: kernel-part-4-addon

      - name: Clone AnyKernel3
        run: git clone --recursive --depth=1 ${{ github.event.inputs.ANYKERNEL_URL }} -b apollo AnyKernel3-${{ matrix.kernel }}

      - name: Move Kernel Files to AnyKernel3
        run: |
          mv kernel-${{ matrix.kernel }}-base/* AnyKernel3-${{ matrix.kernel }}/
          mv kernel-part-1-addon/* AnyKernel3-${{ matrix.kernel }}/
          mv kernel-part-2-addon/* AnyKernel3-${{ matrix.kernel }}/
          mv kernel-part-3-addon/* AnyKernel3-${{ matrix.kernel }}/
          mv kernel-part-4-addon/* AnyKernel3-${{ matrix.kernel }}/

      - name: Define ZIP Name
        run: |
          COMPILED_DATE=$(date +%Y%m%d)
          EXTRA=""
          if [[ "${{ github.event.inputs.OPLUS_FEATURES }}" == "yes" ]]; then
            EXTRA="-OPLUS"
          fi
          if [[ "${{ matrix.kernel }}" == "1" ]]; then
            echo "ZIP_NAME=[FD-][next-${{ github.event.inputs.CODENAME }}-${COMPILED_DATE}${EXTRA}]" >> $GITHUB_ENV
          elif [[ "${{ matrix.kernel }}" == "2" ]]; then
            echo "ZIP_NAME=[FD-][susfs-${{ github.event.inputs.CODENAME }}-${COMPILED_DATE}${EXTRA}]" >> $GITHUB_ENV
          else
            echo "ZIP_NAME=[FD-][noksu-${{ github.event.inputs.CODENAME }}-${COMPILED_DATE}${EXTRA}]" >> $GITHUB_ENV
          fi
      
      - name: Upload Flashable Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: |
            AnyKernel3-${{ matrix.kernel }}/
            !AnyKernel3-${{ matrix.kernel }}/.git
            !AnyKernel3-${{ matrix.kernel }}/.github
      
